In [15]:
import numpy as np
from keras.models import Sequential 
from keras.layers import Dense,SimpleRNN



In [16]:
def rnnModel():
  model=Sequential()
  model.add(SimpleRNN(2,input_shape=(3,1),activation='relu'))
  model.add(Dense(1,activation='relu'))
  model.compile(loss='mean_squared_error',optimizer='adam')
  return model

In [17]:
rnn_model=rnnModel()

In [18]:
rnn_model.weights

[<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/kernel:0' shape=(1, 2) dtype=float32, numpy=array([[-0.8758813 , -0.47227162]], dtype=float32)>,
 <tf.Variable 'simple_rnn_1/simple_rnn_cell_1/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.14093614, -0.9900186 ],
        [ 0.9900186 ,  0.14093627]], dtype=float32)>,
 <tf.Variable 'simple_rnn_1/simple_rnn_cell_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.73256886],
        [ 0.86240304]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [19]:
wx =rnn_model.get_weights()[0]
wh=rnn_model.get_weights()[1]
bh=rnn_model.get_weights()[2]
wy=rnn_model.get_weights()[3]
by=rnn_model.get_weights()[4]

In [20]:
print(f'wx= {wx} , wy ={wy} , bh={bh}, wh={wh} , by = {by}')

wx= [[-0.8758813  -0.47227162]] , wy =[[-0.73256886]
 [ 0.86240304]] , bh=[0. 0.], wh=[[ 0.14093614 -0.9900186 ]
 [ 0.9900186   0.14093627]] , by = [0.]


In [21]:
x=np.array([1,2,3])
x_input=np.reshape(x,[1,3,1])
y_pred=rnn_model.predict(x_input)
y_pred

array([[0.]], dtype=float32)

In [22]:
x

array([1, 2, 3])

In [23]:
m=2
h0=np.zeros(m)
h1=np.dot(x[0],wx) +h0+bh
h2=np.dot(x[1],wx)+np.dot(h1,wh)+bh
h3=np.dot(x[2],wx) +np.dot(h2,wh)+bh
output=np.dot(h3,wy)+by
print(f'h1 = {h1} , h2= {h2} , h3={h3}')

h1 = [[-0.87588131 -0.47227162]] , h2= [[-2.34276365 -0.14396465]] , h3=[[-3.10035168  0.8822749 ]]


In [24]:
print(f'Output  from our calculation : {output}')

Output  from our calculation : [[3.03209764]]


In [25]:
print(f'output from network : {y_pred}')

output from network : [[0.]]
